codecov:
  token: "0471f197-8230-4bc5-a8f6-4fefdd8ae903"

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 100%


ignore:
  - "node_modules"
  - "tests"

comment:
  layout: "diff, flags, files"
