name: GCP Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deployer:
    runs-on: ubuntu-latest

    steps:
      - name: Init repository
        uses: actions/checkout@v4

      - name: Init node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Réalisations des tests
        run: echo "Tests en cours" && npm test

      - name: Get commit author name
        run: |
          AUTHOR_NAME="${{ github.event.commits[0].author.name }}"
          echo "Original author name: $AUTHOR_NAME"
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          PROCESSED_AUTHOR_NAME="${AUTHOR_NAME,,}"
          PROCESSED_AUTHOR_NAME="${PROCESSED_AUTHOR_NAME// /-}"
          echo "Processed Author Name: $PROCESSED_AUTHOR_NAME"
          echo "processed_author_name=$PROCESSED_AUTHOR_NAME" >> $GITHUB_ENV

      - name: Get commit author
        run: echo "Pipeline triggered by $processed_author_name"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Authentification auprès de GCP
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.svcaccount }}
          project_id: galvanized-math-423308-t4
          export_default_credentials: true

      - name: Déploiement sur GCP
        run: echo "Déploiement en cours..." && gcloud functions deploy node-function --gen2 --runtime=nodejs20 --region=us-east1 --source=. --entry-point=app --trigger-http --update-labels=deployed_by=$processed_author_name
