name: GCP Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deployer:
    runs-on: ubuntu-latest

    steps:
      - name: Réalisations des tests
        run: echo "Tests en cours" && npm run test

      - name: Get commit author
        run: echo "Pipeline triggered by ${{ github.event.commits[0].author.name }}"

      - name: Authentification auprès de GCP
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: 'latest'
          google-auth-token: ${{ secrets.svcaccount }}
          project-id: galvanized-math-423308-t4

      - name: Déploiement sur GCP
        run: echo "Déploiement en cours..." && gcloud functions deploy node-function --gen2 --runtime=nodejs20 --region=us-east1 --source=. --entry-point=app --trigger-http --update-labels=deployed_by=github